version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - monreseau
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - monreseau
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  app:
    build: ./app
    container_name: app
    ports:
      - "8080:80"
    networks:
      - monreseau
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  db_data:

networks:
  monreseau:
